version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR on `date`
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 165312476418.dkr.ecr.ap-south-1.amazonaws.com
      - echo setting repository URI...
      - REPOSITORY_URI=165312476418.dkr.ecr.ap-south-1.amazonaws.com/cicdpipeline
      - echo setting image tag...
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - echo Tagging Docker image...
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo pushing Docker image to AWS ECR started on `date`
      - echo Pushing the Docker images to repository...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo setting container name...
      - DOCKER_CONTAINER_NAME=cdcicontainer
      - echo writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
   files:
      - imagedefinitions.json
      